# Generated by Django 5.2.3 on 2025-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_event.jpg', null=True, upload_to='event_asset/'),
        ),
    ]
